name: set-up
description: |
  This action set up the environment for the project.

inputs:
  node-version:
    description: "Node.js version to use"
    default: "18"
    required: false

runs:
  using: "composite"
  steps:
    # Rust
    - name: Set up
      uses: ./.github/actions/set-up
    # NPM cache
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
    - name: Install Node.js dependencies
      run: npm i # We can't do `npm ci` because of a bug where NPM doesn't pull down the right rollup binary
      shell: bash
