/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the health of the system */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthCheckResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of available models */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ModelDefinition"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/observability/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the logs from the system */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["LogResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of tasks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_TaskInfo"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a task */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["int64"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a list of task runs */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["TaskRunListRequest"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_TaskRunInfo"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/run/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a task run by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TaskRun"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a task by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Update a task */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    /** Delete a task */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a task by ID */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Map_of_AnyValue"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Map_of_AnyValue"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the input and output JSON Schemas for a task */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["InputAndOutputSchema"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of available tools */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ToolDefinition"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the version of the server */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["string"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Array_of_ModelDefinition: components["schemas"]["ModelDefinition"][];
    Array_of_TaskInfo: components["schemas"]["TaskInfo"][];
    Array_of_TaskRunInfo: components["schemas"]["TaskRunInfo"][];
    Array_of_ToolDefinition: components["schemas"]["ToolDefinition"][];
    /** @description An error message. */
    Error: {
      /** @description The error message. */
      error: string;
    };
    /** @description Response to a health check request. */
    HealthCheckResponse: Record<string, never>;
    /** @description Input and output schemas. */
    InputAndOutputSchema: {
      /** @description The input schema for a task. */
      inputSchema: {
        [key: string]: unknown;
      };
      /** @description The output schema for a task. */
      outputSchema: {
        [key: string]: unknown;
      };
    };
    /** @description The log level. */
    LogLevel: string;
    /** @description A logged message. */
    LogMessage: {
      /** @description Structured logging fields. */
      fields: {
        [key: string]: unknown;
      };
      level: components["schemas"]["LogLevel"];
      /**
       * Format: uint32
       * @description The line number where the log message was emitted.
       */
      line?: number | null;
      /** @description The module where the log message was emitted. */
      module: string;
      /**
       * Format: uint64
       * @description The number of seconds since epoch.
       */
      timestampS: number;
    };
    /** @description A list of logged messages. */
    LogResponse: components["schemas"]["LogMessage"][];
    Map_of_AnyValue: {
      [key: string]: unknown;
    };
    /** @description A model definition. */
    ModelDefinition: {
      /** @description The human-friendly name of the model. */
      name: string;
      /** @description The URI of the model. */
      uri: string;
    };
    /** @description Status of a run of a step or task. */
    RunStatus: string;
    /** @description A step of a task. */
    Step: {
      /**
       * Format: int64
       * @description The end time of the step in milliseconds since UTC epoch.
       */
      endTimeMs?: number | null;
      /** @description The inputs to the tool. */
      inputs: unknown;
      /** @description The outputs from the tool. */
      outputs: unknown;
      /** Format: int64 */
      parentStepId?: number | null;
      /**
       * Format: int64
       * @description The start of the step in milliseconds since UTC epoch.
       */
      startTimeMs?: number | null;
      stepAction: components["schemas"]["StepAction"];
      /** Format: int64 */
      stepId: number;
    };
    /** @description A step of a task run. */
    StepAction:
      | {
          /** Format: int64 */
          taskId: number;
        }
      | {
          toolId: string;
        };
    /** @description A task is the smallest unit of work in a workflow. */
    Task: {
      /**
       * @description The IDs of tools to make available to the LLM.
       * @default []
       */
      availableToolIds: string[];
      /**
       * @description The input schema of a task.
       *
       *      Each key in this object should be a variable name in `template`.
       * @default {}
       */
      inputSchema: {
        [key: string]: unknown;
      };
      /** @description The name of the task. */
      name: string;
      /** @description The output schema.
       *
       *      If unspecified the task will return an object with a single "output" string. */
      outputSchema?: {
        [key: string]: unknown;
      } | null;
      template: components["schemas"]["Template"];
    };
    /** @description Minimal information describing a stored task. */
    TaskInfo: {
      /**
       * Format: int64
       * @description The ID of the task.
       *
       *      This ID can be used to retrieve the contents of the task.
       */
      id: number;
      /** @description The name of the task. */
      name: string;
    };
    /** @description A run of a task. */
    TaskRun: {
      /**
       * Format: int64
       * @description The end time of the run in milliseconds since UTC epoch.
       */
      endTimeMs?: number | null;
      /**
       * Format: int64
       * @description The ID of the run.
       */
      id: number;
      /**
       * Format: int64
       * @description The start of the run in milliseconds since UTC epoch.
       */
      startTimeMs?: number | null;
      status: components["schemas"]["RunStatus"];
      /** @description The steps in the run. */
      steps: components["schemas"]["Step"][];
    };
    /** @description Information about a task run. */
    TaskRunInfo: {
      /**
       * Format: int64
       * @description The end time of the run in milliseconds since UTC epoch.
       */
      endTimeMs?: number | null;
      /**
       * Format: int64
       * @description The ID of the run.
       */
      id: number;
      /**
       * Format: int64
       * @description The start of the run in milliseconds since UTC epoch.
       */
      startTimeMs?: number | null;
      status: components["schemas"]["RunStatus"];
    };
    /** @description A request to list task runs. */
    TaskRunListRequest: {
      /**
       * Format: int64
       * @description How many task runs to list.
       * @default 100
       */
      limit: number;
    };
    /** @description A template.
     *
     *      Variables in templates are defined using `${variableName}` syntax. */
    Template: string;
    /** @description A tool definition. */
    ToolDefinition: {
      /** @description A detailed description of what the tool does. */
      description: string;
      /** @description A unique ID for the tool.. */
      id: string;
      /** @description A JSON Schema describing the parameters for the tool.
       *
       *      See <https://json-schema.org/>. */
      inputSchema: unknown;
      /** @description The name of the tool.
       *
       *      Must match `^[a-zA-Z0-9_-]{1,64}$`. */
      name: string;
      /** @description The source that provides the tool. */
      provider: string;
    };
    /** Format: int64 */
    int64: number;
    string: string;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
