/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the health of the system */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthCheckResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of available models */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ModelDefinition"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/observability/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the logs from the system */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["LogResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of tasks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ObjectInfo"];
          };
        };
      };
    };
    put?: never;
    /** Create a task */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["int64"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a task by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Task"];
          };
        };
      };
    };
    put?: never;
    /** Update a task */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Task"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Delete a task */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/task/{id}/inputSchema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the input JSON Schema for a task */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Map_of_AnyValue"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of available tools */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ToolDefinition"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workflow": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of workflows */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Array_of_ObjectInfo"];
          };
        };
      };
    };
    put?: never;
    /** Create a workflow */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Workflow"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["int64"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workflow/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a workflow by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Workflow"];
          };
        };
      };
    };
    put?: never;
    /** Update a workflow */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Workflow"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Delete a workflow */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/workflow/{id}/invoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invoke a workflow by ID */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Map_of_AnyValue"];
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Map_of_AnyValue"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Array_of_ModelDefinition: components["schemas"]["ModelDefinition"][];
    Array_of_ObjectInfo: components["schemas"]["ObjectInfo"][];
    Array_of_ToolDefinition: components["schemas"]["ToolDefinition"][];
    /** @description A connection. */
    Connection:
      | {
          /** @description The name of the parameter. */
          parameter: string;
          /** @description The task parameters to connect the workflow parameter to. */
          to: string[];
        }
      | {
          /** @description The ID of the task that produces the output. */
          from: string;
          /** @description The ID of the task that consumes the output. */
          to: string[];
        };
    /** @description Response to a health check request. */
    HealthCheckResponse: Record<string, never>;
    /** @description Run an LLM. */
    InvokeLLM: {
      modelStrength: components["schemas"]["ModelStrength"];
      template: components["schemas"]["Template"];
    };
    /** @description The log level. */
    LogLevel: string;
    /** @description A logged message. */
    LogMessage: {
      /** @description Structured logging fields. */
      fields: {
        [key: string]: unknown;
      };
      level: components["schemas"]["LogLevel"];
      /**
       * Format: uint32
       * @description The line number where the log message was emitted.
       */
      line?: number | null;
      /** @description The module where the log message was emitted. */
      module: string;
      /**
       * Format: uint64
       * @description The number of seconds since epoch.
       */
      timestampS: number;
    };
    /** @description A list of logged messages. */
    LogResponse: components["schemas"]["LogMessage"][];
    Map_of_AnyValue: {
      [key: string]: unknown;
    };
    /** @description A model definition. */
    ModelDefinition: {
      /** @description The human-friendly name of the model. */
      name: string;
      /** @description The URI of the model. */
      uri: string;
    };
    /** @description Enum for model strength. */
    ModelStrength: string;
    /** @description Minimal information describing a stored object. */
    ObjectInfo: {
      /**
       * Format: int64
       * @description The ID of the object.
       *
       *      This ID can be used to retrieve the contents of the object.
       */
      id: number;
      /** @description The name of the object. */
      name: string;
    };
    /** @description A task is the smallest unit of work in a workflow. */
    Task: {
      action: components["schemas"]["TaskAction"];
      /** @description The name of the task. */
      name: string;
    };
    /** @description A description of the action associated with a task. */
    TaskAction: {
      invokeLLM: components["schemas"]["InvokeLLM"];
    };
    /** @description A task ID. */
    TaskId: {
      /**
       * Format: int64
       * @description The ID of the task.
       */
      taskId: number;
    };
    /** @description A template written with Jinja2 syntax. */
    Template: string;
    /** @description A tool definition. */
    ToolDefinition: {
      /** @description A detailed description of what the tool does. */
      description: string;
      /** @description A JSON Schema describing the parameters for the tool.
       *
       *      See <https://json-schema.org/>. */
      inputSchema: unknown;
      /** @description The name of the tool.
       *
       *      Must match `^[a-zA-Z0-9_-]{1,64}$`. */
      name: string;
    };
    /** @description A workflow. */
    Workflow: {
      /** @description The tasks in the workflow.
       *
       *      The keys are the IDs of the tasks. */
      actions: {
        [key: string]: components["schemas"]["WorkflowAction"];
      };
      /**
       * @description A mapping of connections between tasks.
       *
       *      # Example
       *
       *      ```json
       *      [
       *        {
       *          // Make the workflow parameter `url` available to the task `foo`.
       *          "parameter": "url",
       *          "to": ["foo.url"]
       *        },
       *        {
       *          // Pipe the output of the `foo` task to the  `content` parameter of task `bar`.
       *          "from": "foo.output",
       *          "to": ["bar.content"]
       *        }
       *      ]
       *      ```
       * @default []
       */
      connections: components["schemas"]["Connection"][];
      /** @description The name of the workflow. */
      name: string;
    };
    /** @description A task a workflow will perform. */
    WorkflowAction:
      | components["schemas"]["TaskId"]
      | components["schemas"]["WorkflowId"]
      | {
          toolId: string;
        };
    /** @description A workflow ID. */
    WorkflowId: {
      /**
       * Format: int64
       * @description The ID of the workflow.
       */
      workflowId: number;
    };
    /** Format: int64 */
    int64: number;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
