version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
      tailwind:
        applies-to: version-updates
        patterns:
          - "@tailwindcss/*"
          - "tailwind-*"
          - "tailwind"
          - "tw-animate-css"
        update-types:
          - "minor"
          - "patch"
      react:
        applies-to: version-updates
        patterns:
          - "@tanstack/*"
          - "@types/react-dom"
          - "@types/react"
          - "react-dom"
          - "react-router"
          - "react"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 1
