[package]
name = "sauropod-tts"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
sauropod-audio.path = "../audio"
sauropod-huggingface.path = "../huggingface"
sauropod-inference-engine-api.path = "../inference-engine-api"
sauropod-inference-engine.path = "../inference-engine"
sauropod-inference-thread.path = "../inference-thread"
sauropod-onnxruntime.path = "../../bindings/onnxruntime"

anyhow.workspace = true
futures-lite.workspace = true
regex.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tokenizers = { workspace = true, features = ["http"] }

[dev-dependencies]
sauropod-hf-test-helpers.path = "../../tools/hf-test-helpers"
sauropod-config.path = "../config"
sauropod-tracing-test-helpers.path = "../../tools/tracing-test-helpers"
tokio.workspace = true
hound = "3.5.1"
