[package]
name = "sauropod-hf-test-helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
hf-hub.workspace = true
symphonia.workspace = true
anyhow.workspace = true
