name: Promote Container Image on Release

on:
  workflow_dispatch:
  release:
    types: [published] # Trigger workflow when a release is published

env:
  # We don't need incremental compilation in CI
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLORS: always

jobs:
  promote-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Rust
        uses: ./.github/actions/set-up-rust
      - name: Set up Docker
        uses: ./.github/actions/set-up-docker
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Promote the latest release image
        run: |
          cargo run -p update-latest-image -- --repo=${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
          RUSTC_WRAPPER: "sccache"
          SCCACHE_GHA_ENABLED: "true"
