name: PR Checks

concurrency:
  # When a new commit is pushed to a pull request, kill the run
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  packages: read

on:
  pull_request:
    branches: [main]

env:
  # We don't need incremental compilation in CI
  CARGO_INCREMENTAL: "0"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up
        uses: ./.github/actions/set-up

      # Pre-commit cache
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Cache pre-commit dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"
